server:
  port: 12000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yulong-sict-ac/spring-cloud-config.git
  rabbitmq:
    host: localhost
    port: 5672
    username: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka

management:
  endpoints:
    web:
      exposure:
        #暴露触发消息总线的地址
        include: bus-refresh